apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mosquitto
  storageClassName: mosquitto-storage-class   # 🧠 Link to the StorageClass

    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: mosquitto-storage-class    # 🧠 Must match
